language: node
node_js:
    - 8.10.0
before_install:
    - rvm install 2.3.3
install:
    - npm install
    - gem install jekyll html-proofer
jobs:
  include:
    - stage: fetch
        script: npm run fetch
    - stage: build
        script: jekyll build
    - stage: test
        script: htmlproofer ./_site --alt-ignore '/.*/'

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master

branches:
  except:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
