language:         ruby
rvm:
- 2.3.3

before_script:
 - chmod +x ./test/travisBuild
script:           ./test/travisBuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo:             false
